USE ROLE SYSADMIN;
USE  DEMO_DB.SILVER;

CREATE OR REPLACE TABLE TABLE_1(
   ID INT,
   RAW VARCHAR,
   UPDATED_AT TIMESTAMP
);

INSERT INTO TABLE_1 (ID, RAW, UPDATED_AT) VALUES
(1, 'I am in SILVER!', CURRENT_TIMESTAMP());