USE ROLE SYSADMIN;
USE  DEMO_DB.BRONZE;

CREATE OR REPLACE TABLE TABLE_2(
   ID INT,
   RAW_2 VARCHAR,
   UPDATED_AT TIMESTAMP
);

INSERT INTO TABLE_2 (ID, RAW, UPDATED_AT) VALUES
(2, 'Hello World!', CURRENT_TIMESTAMP());