USE ROLE SYSADMIN;
USE DEMO_DB.BRONZE;

ALTER TABLE TABLE_2
ADD COLUMN RAW_2 VARCHAR;

INSERT INTO TABLE_2 (ID, RAW, UPDATED_AT, RAW_2) VALUES
(3, 'New Field Added!', CURRENT_TIMESTAMP(), 'NEW VALUE');