USE ROLE SYSADMIN;
USE  DEMO_DB.GOLD;

CREATE OR REPLACE TABLE TEST_TABLE(
   ID INT,
   RAW VARCHAR,
   UPDATED_AT TIMESTAMP
);

INSERT INTO TEST_TABLE (ID, RAW, UPDATED_AT) VALUES
(1, 'I am in GOLD!', CURRENT_TIMESTAMP());