USE ROLE SYSADMIN;
USE  DEMO_DB.SILVER;

CREATE OR REPLACE TABLE TABLE_2(
   ID INT,
   RAW VARCHAR,
   UPDATED_AT TIMESTAMP
);

INSERT INTO TABLE_2 (ID, RAW, UPDATED_AT) VALUES
(2, 'I am in SILVER!', CURRENT_TIMESTAMP());